### ISSUE TITLE
Choose subject for 2015-01-31 live session

### ISSUE THREAD

**Issue by openspectrum** [codeunion/fundamentals-of-web-development#159]
Trying someting new here. For the next saturday live session, I'll be taking suggetions for what to cover. It's choose your own adventure time!

Please comment on this issue with your requests for this session. Good requests will include:

- A **specific skill or topic** to explore (i.e. stack traces in Ruby error messages)
- Suggestion for **a project to build** together (i.e. let's write a web scraper for Craigslist)
- Big, Difficult **Questions** with hard-to-comprehend answers, even after much research and discussion on Slack and/or feedback requests (i.e. what is the difference between compiled and interpreted langauges)

**Comment by mjgold** [comment]
Two areas I'd to learn more about:

-Debugging techniques (with or without an IDE)
-Best practices in designing objects (e.g. what to put in instance variables vs. method parameters)

**Comment by ric-reyes** [comment]
I could use some greater clarity on Ruby classes and how/when to build/use them.

**Comment by openspectrum** [comment]
Done and done! Notes and code from session here: https://github.com/codeunion/fundamentals-of-web-development/tree/master/session-notes/2015-01-31
